/*
 * Copyright (c) 2015 Cryptonomex, Inc., and contributors.
 *
 * The MIT License
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include <evolution/chain/get_config.hpp>
#include <evolution/chain/config.hpp>
#include <evolution/chain/protocol/types.hpp>

namespace evolution { namespace chain {

fc::variant_object get_config()
{
   fc::mutable_variant_object result;

   result[ "EVOLUTION_SYMBOL" ] = EVOLUTION_SYMBOL;
   result[ "EVOLUTION_ADDRESS_PREFIX" ] = EVOLUTION_ADDRESS_PREFIX;
   result[ "EVOLUTION_MIN_ACCOUNT_NAME_LENGTH" ] = EVOLUTION_MIN_ACCOUNT_NAME_LENGTH;
   result[ "EVOLUTION_MAX_ACCOUNT_NAME_LENGTH" ] = EVOLUTION_MAX_ACCOUNT_NAME_LENGTH;
   result[ "EVOLUTION_MIN_ASSET_SYMBOL_LENGTH" ] = EVOLUTION_MIN_ASSET_SYMBOL_LENGTH;
   result[ "EVOLUTION_MAX_ASSET_SYMBOL_LENGTH" ] = EVOLUTION_MAX_ASSET_SYMBOL_LENGTH;
   result[ "EVOLUTION_MAX_SHARE_SUPPLY" ] = EVOLUTION_MAX_SHARE_SUPPLY;
   result[ "EVOLUTION_MAX_PAY_RATE" ] = EVOLUTION_MAX_PAY_RATE;
   result[ "EVOLUTION_MAX_SIG_CHECK_DEPTH" ] = EVOLUTION_MAX_SIG_CHECK_DEPTH;
   result[ "EVOLUTION_MIN_TRANSACTION_SIZE_LIMIT" ] = EVOLUTION_MIN_TRANSACTION_SIZE_LIMIT;
   result[ "EVOLUTION_MIN_BLOCK_INTERVAL" ] = EVOLUTION_MIN_BLOCK_INTERVAL;
   result[ "EVOLUTION_MAX_BLOCK_INTERVAL" ] = EVOLUTION_MAX_BLOCK_INTERVAL;
   result[ "EVOLUTION_DEFAULT_BLOCK_INTERVAL" ] = EVOLUTION_DEFAULT_BLOCK_INTERVAL;
   result[ "EVOLUTION_DEFAULT_MAX_TRANSACTION_SIZE" ] = EVOLUTION_DEFAULT_MAX_TRANSACTION_SIZE;
   result[ "EVOLUTION_DEFAULT_MAX_BLOCK_SIZE" ] = EVOLUTION_DEFAULT_MAX_BLOCK_SIZE;
   result[ "EVOLUTION_DEFAULT_MAX_TIME_UNTIL_EXPIRATION" ] = EVOLUTION_DEFAULT_MAX_TIME_UNTIL_EXPIRATION;
   result[ "EVOLUTION_DEFAULT_MAINTENANCE_INTERVAL" ] = EVOLUTION_DEFAULT_MAINTENANCE_INTERVAL;
   result[ "EVOLUTION_DEFAULT_MAINTENANCE_SKIP_SLOTS" ] = EVOLUTION_DEFAULT_MAINTENANCE_SKIP_SLOTS;
   result[ "EVOLUTION_MIN_UNDO_HISTORY" ] = EVOLUTION_MIN_UNDO_HISTORY;
   result[ "EVOLUTION_MAX_UNDO_HISTORY" ] = EVOLUTION_MAX_UNDO_HISTORY;
   result[ "EVOLUTION_MIN_BLOCK_SIZE_LIMIT" ] = EVOLUTION_MIN_BLOCK_SIZE_LIMIT;
   result[ "EVOLUTION_MIN_TRANSACTION_EXPIRATION_LIMIT" ] = EVOLUTION_MIN_TRANSACTION_EXPIRATION_LIMIT;
   result[ "EVOLUTION_BLOCKCHAIN_PRECISION" ] = EVOLUTION_BLOCKCHAIN_PRECISION;
   result[ "EVOLUTION_BLOCKCHAIN_PRECISION_DIGITS" ] = EVOLUTION_BLOCKCHAIN_PRECISION_DIGITS;
   result[ "EVOLUTION_DEFAULT_TRANSFER_FEE" ] = EVOLUTION_DEFAULT_TRANSFER_FEE;
   result[ "EVOLUTION_MAX_INSTANCE_ID" ] = EVOLUTION_MAX_INSTANCE_ID;
   result[ "EVOLUTION_100_PERCENT" ] = EVOLUTION_100_PERCENT;
   result[ "EVOLUTION_1_PERCENT" ] = EVOLUTION_1_PERCENT;
   result[ "EVOLUTION_MAX_MARKET_FEE_PERCENT" ] = EVOLUTION_MAX_MARKET_FEE_PERCENT;
   result[ "EVOLUTION_DEFAULT_FORCE_SETTLEMENT_DELAY" ] = EVOLUTION_DEFAULT_FORCE_SETTLEMENT_DELAY;
   result[ "EVOLUTION_DEFAULT_FORCE_SETTLEMENT_OFFSET" ] = EVOLUTION_DEFAULT_FORCE_SETTLEMENT_OFFSET;
   result[ "EVOLUTION_DEFAULT_FORCE_SETTLEMENT_MAX_VOLUME" ] = EVOLUTION_DEFAULT_FORCE_SETTLEMENT_MAX_VOLUME;
   result[ "EVOLUTION_DEFAULT_PRICE_FEED_LIFETIME" ] = EVOLUTION_DEFAULT_PRICE_FEED_LIFETIME;
   result[ "EVOLUTION_MAX_FEED_PRODUCERS" ] = EVOLUTION_MAX_FEED_PRODUCERS;
   result[ "EVOLUTION_DEFAULT_MAX_AUTHORITY_MEMBERSHIP" ] = EVOLUTION_DEFAULT_MAX_AUTHORITY_MEMBERSHIP;
   result[ "EVOLUTION_DEFAULT_MAX_ASSET_WHITELIST_AUTHORITIES" ] = EVOLUTION_DEFAULT_MAX_ASSET_WHITELIST_AUTHORITIES;
   result[ "EVOLUTION_DEFAULT_MAX_ASSET_FEED_PUBLISHERS" ] = EVOLUTION_DEFAULT_MAX_ASSET_FEED_PUBLISHERS;
   result[ "EVOLUTION_COLLATERAL_RATIO_DENOM" ] = EVOLUTION_COLLATERAL_RATIO_DENOM;
   result[ "EVOLUTION_MIN_COLLATERAL_RATIO" ] = EVOLUTION_MIN_COLLATERAL_RATIO;
   result[ "EVOLUTION_MAX_COLLATERAL_RATIO" ] = EVOLUTION_MAX_COLLATERAL_RATIO;
   result[ "EVOLUTION_DEFAULT_MAINTENANCE_COLLATERAL_RATIO" ] = EVOLUTION_DEFAULT_MAINTENANCE_COLLATERAL_RATIO;
   result[ "EVOLUTION_DEFAULT_MAX_SHORT_SQUEEZE_RATIO" ] = EVOLUTION_DEFAULT_MAX_SHORT_SQUEEZE_RATIO;
   result[ "EVOLUTION_DEFAULT_MARGIN_PERIOD_SEC" ] = EVOLUTION_DEFAULT_MARGIN_PERIOD_SEC;
   result[ "EVOLUTION_DEFAULT_MAX_DELEGATES" ] = EVOLUTION_DEFAULT_MAX_DELEGATES;
   result[ "EVOLUTION_DEFAULT_MAX_COMMITTEE" ] = EVOLUTION_DEFAULT_MAX_COMMITTEE;
   result[ "EVOLUTION_DEFAULT_MAX_PROPOSAL_LIFETIME_SEC" ] = EVOLUTION_DEFAULT_MAX_PROPOSAL_LIFETIME_SEC;
   result[ "EVOLUTION_DEFAULT_COMMITTEE_PROPOSAL_REVIEW_PERIOD_SEC" ] = EVOLUTION_DEFAULT_COMMITTEE_PROPOSAL_REVIEW_PERIOD_SEC;
   result[ "EVOLUTION_DEFAULT_NETWORK_PERCENT_OF_FEE" ] = EVOLUTION_DEFAULT_NETWORK_PERCENT_OF_FEE;
   result[ "EVOLUTION_DEFAULT_LIFETIME_REFERRER_PERCENT_OF_FEE" ] = EVOLUTION_DEFAULT_LIFETIME_REFERRER_PERCENT_OF_FEE;
   result[ "EVOLUTION_DEFAULT_MAX_BULK_DISCOUNT_PERCENT" ] = EVOLUTION_DEFAULT_MAX_BULK_DISCOUNT_PERCENT;
   result[ "EVOLUTION_DEFAULT_BULK_DISCOUNT_THRESHOLD_MIN" ] = EVOLUTION_DEFAULT_BULK_DISCOUNT_THRESHOLD_MIN;
   result[ "EVOLUTION_DEFAULT_BULK_DISCOUNT_THRESHOLD_MAX" ] = EVOLUTION_DEFAULT_BULK_DISCOUNT_THRESHOLD_MAX;
   result[ "EVOLUTION_DEFAULT_CASHBACK_VESTING_PERIOD_SEC" ] = EVOLUTION_DEFAULT_CASHBACK_VESTING_PERIOD_SEC;
   result[ "EVOLUTION_DEFAULT_CASHBACK_VESTING_THRESHOLD" ] = EVOLUTION_DEFAULT_CASHBACK_VESTING_THRESHOLD;
   result[ "EVOLUTION_DEFAULT_BURN_PERCENT_OF_FEE" ] = EVOLUTION_DEFAULT_BURN_PERCENT_OF_FEE;
   result[ "EVOLUTION_DELEGATE_PAY_PERCENT_PRECISION" ] = EVOLUTION_DELEGATE_PAY_PERCENT_PRECISION;
   result[ "EVOLUTION_DEFAULT_MAX_ASSERT_OPCODE" ] = EVOLUTION_DEFAULT_MAX_ASSERT_OPCODE;
   result[ "EVOLUTION_DEFAULT_FEE_LIQUIDATION_THRESHOLD" ] = EVOLUTION_DEFAULT_FEE_LIQUIDATION_THRESHOLD;
   result[ "EVOLUTION_DEFAULT_ACCOUNTS_PER_FEE_SCALE" ] = EVOLUTION_DEFAULT_ACCOUNTS_PER_FEE_SCALE;
   result[ "EVOLUTION_DEFAULT_ACCOUNT_FEE_SCALE_BITSHIFTS" ] = EVOLUTION_DEFAULT_ACCOUNT_FEE_SCALE_BITSHIFTS;
   result[ "EVOLUTION_MAX_WORKER_NAME_LENGTH" ] = EVOLUTION_MAX_WORKER_NAME_LENGTH;
   result[ "EVOLUTION_MAX_URL_LENGTH" ] = EVOLUTION_MAX_URL_LENGTH;
   result[ "EVOLUTION_NEAR_SCHEDULE_CTR_IV" ] = EVOLUTION_NEAR_SCHEDULE_CTR_IV;
   result[ "EVOLUTION_FAR_SCHEDULE_CTR_IV" ] = EVOLUTION_FAR_SCHEDULE_CTR_IV;
   result[ "EVOLUTION_CORE_ASSET_CYCLE_RATE" ] = EVOLUTION_CORE_ASSET_CYCLE_RATE;
   result[ "EVOLUTION_CORE_ASSET_CYCLE_RATE_BITS" ] = EVOLUTION_CORE_ASSET_CYCLE_RATE_BITS;
   result[ "EVOLUTION_DEFAULT_DELEGATE_PAY_PER_BLOCK" ] = EVOLUTION_DEFAULT_DELEGATE_PAY_PER_BLOCK;
   result[ "EVOLUTION_DEFAULT_DELEGATE_PAY_VESTING_SECONDS" ] = EVOLUTION_DEFAULT_DELEGATE_PAY_VESTING_SECONDS;
   result[ "EVOLUTION_DEFAULT_WORKER_BUDGET_PER_DAY" ] = EVOLUTION_DEFAULT_WORKER_BUDGET_PER_DAY;
   result[ "EVOLUTION_MAX_INTEREST_APR" ] = EVOLUTION_MAX_INTEREST_APR;
   result[ "EVOLUTION_COMMITTEE_ACCOUNT" ] = EVOLUTION_COMMITTEE_ACCOUNT;
   result[ "EVOLUTION_DELEGATE_ACCOUNT" ] = EVOLUTION_DELEGATE_ACCOUNT;
   result[ "EVOLUTION_RELAXED_COMMITTEE_ACCOUNT" ] = EVOLUTION_RELAXED_COMMITTEE_ACCOUNT;
   result[ "EVOLUTION_NULL_ACCOUNT" ] = EVOLUTION_NULL_ACCOUNT;
   result[ "EVOLUTION_TEMP_ACCOUNT" ] = EVOLUTION_TEMP_ACCOUNT;

   return result;
}

} } // evolution::chain
